# Generated by Django 3.1 on 2020-10-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='motor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merek', models.CharField(max_length=200)),
                ('kecepatan', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
    ]
